---
title: "qc"
output:
  html_document:
    self_contained: true
    toc: true
    toc_depth: 2
    toc_float: true
params:
  db: db
  fsheet_def: fsheet_def
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hms)
```



```{r, results='asis'}
categorical_table <- function(x){
      if (any(!is.na(x$value_as_logical))){
      x %>%
        count(value_as_logical, value_as_character) %>%
        knitr::kable() %>%
        print()
      cat("\n")
    }
}

tests_plot <- function(x, group, tests_def){
  s <- group$symbol
  def <- tests_def[[s]]
  if (nrow(x) > 0){
    title <- def$title
    range_mainly_low <- def$range_mainly_low
    range_mainly_high <- def$range_mainly_high
    range_discard_below <- as.numeric(def$range_discard_below)
    range_discard_above <- as.numeric(def$range_discard_above)
    names_cuh <- def$names_cuh

    title <- glue("{title} [{unique(group$symbol)}]")
    cat("\n\n##   ", title, "\n\n")

    df <-
      tribble(~name, ~value,
              "CUH names", paste0("\"", names_cuh, "\"", collapse = ","),
                "Number of rows", as.character(nrow(x)))

    df %>%
      knitr::kable() %>%
        print()
      cat("\n")

    if (any(x$type == "numeric")){
      print(tests_plot_numeric(x, range_mainly_low, range_mainly_high, range_discard_below, range_discard_above))
    }

    categorical_table(x)

    x <- x %>%
      mutate(datetime = if_else(!is.na(collected_datetime),
                                collected_datetime,
                                result_datetime))

    plot_time_of_day <- tests_histogram_time_of_day(x)
    plot_by_date <- tests_histogram_by_date(x)
    plot_by_weekday <- tests_histogram_by_weekday(x)

    time_plot <- (plot_time_of_day + plot_by_weekday) / plot_by_date
    print(time_plot)
  }
}
```

# Flowsheets

```{r,results='asis'}

fsheet_plot <- function(x, symbol, tests_def){
  def <- tests_def[[symbol]]
  if (nrow(x) > 0){
    title <- def$title
    range_mainly_low <- as.numeric(def$range_mainly_low)
    range_mainly_high <- as.numeric(def$range_mainly_high)
    range_discard_below <- as.numeric(def$range_discard_below)
    range_discard_above <- as.numeric(def$range_discard_above)
    names_cuh <- def$names_cuh

    title <- glue("{title} [{unique(symbol)}]")
    cat("\n\n##   ", title, "\n\n")

    df <-
      tribble(~name, ~value,
              "CUH names", paste0("\"", names_cuh, "\"", collapse = ","),
                "Number of rows", as.character(nrow(x)))

    df %>%
      knitr::kable() %>%
        print()
      cat("\n")

    if (any(x$type == "numeric")){
      print(tests_plot_numeric(x, range_mainly_low, range_mainly_high, range_discard_below, range_discard_above))
    }

    categorical_table(x)

    x <- x %>%
      mutate(datetime = measurement_datetime)

    plot_time_of_day <- tests_histogram_time_of_day(x)
    plot_by_date <- tests_histogram_by_date(x)
    plot_by_weekday <- tests_histogram_by_weekday(x)

    time_plot <- (plot_time_of_day + plot_by_weekday) / plot_by_date
    print(time_plot)
  }
}

fsheet_db <- tbl(db, "fsheet")
nrow_fsheet <- fsheet_db %>%
  count() %>%
  pull(n)


if (nrow_fsheet > 0){
  symbols <- fsheet_db %>%
    count(symbol) %>%
    pull(symbol)

  for (this_symbol in symbols){
    fsheet_symbol <- fsheet_db %>%
      filter(symbol == this_symbol) %>%
      collect()
    
    fsheet_plot(fsheet_symbol, this_symbol, fsheet_def)
  }
  # fsheet_db %>%
  #   group_by(symbol) %>%
  #   group_walk(~ fsheet_plot(.x, .y, fsheet_def))
}
```

